# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: pre-commit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@8c5fe0f3eb42d9eb5e0d110929cbefd0f8670f86 # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@8c5fe0f3eb42d9eb5e0d110929cbefd0f8670f86 # develop
