# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: pre-commit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@9dc708a869815c0f91d4e56db5eae00e390ffbf1 # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@9dc708a869815c0f91d4e56db5eae00e390ffbf1 # develop
